ionic-workers:
   image: ajjenda/ionic-workers:latest
   expose:
    - "8100"
    - "35729"
   restart: always
   tty: true
   stdin_open: true
workers:
  ports:
  - 35731:35729/tcp
  - 8102:8100
  restart: always
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
  links:
  - ionic-workers:ionic-workers  
